# =========================
# PATHS
# =========================
paths:
  # --- Data Directories ---
  data_hover_comsol:   "../Experiment/data/hover/comsol"
  data_hover_raw:   "../Experiment/data/hover/raw"
  data_hover_tare:  "../Experiment/data/hover/tare"
  data_cruise_comsol:   "../Experiment/data/cruise/comsol"
  data_cruise_raw:  "../Experiment/data/cruise/raw"
  data_cruise_tare: "../Experiment/data/cruise/tare"
  data_processed_dir: "../Experiment/data/processed" # Renamed for clarity

  # --- Key File Paths ---
  master_parquet:   "../Experiment/data/processed/master_dataset.parquet"
  doe_csv:          "../Experiment/doe/doe_test_plan_01.csv"

  # --- Output Directories ---
  outputs_models:   "../Experiment/outputs/models"
  outputs_plots:    "../Experiment/outputs/plots"
  outputs_tables:   "../Experiment/outputs/tables"

# =========================
# DATA PROCESSING PARAMETERS
# =========================
hover_process:
  # SNR thresholds for automatic data filtering
  thrust_snr_threshold: 4.29
  torque_snr_threshold: 4.29

# =========================
# FLUIDS
# =========================
fluids:
  rho: 1.204   # kg/m^3 density of air at 20C, 1 atm
  mu:  1.81e-5 # Pa·s dynamic viscosity of air at 20C, 1 atm

# =========================
# GEOMETRY (global constants)
# =========================
geometry:
  r_hub_m:        0.046      # hub radius (m)
  span_blade_m:   0.184      # blade span (m) -> r_tip = r_hub_m + span_blade_m
  n_blades:       2          # number of blades

# =========================
# MODEL FEATURES & BOUNDS
# =========================
geometry_cols: ["AR", "lambda", "aoa_root (deg)", "twist (deg)"]

# =========================
# OPTIMIZATION PARAMETERS
# =========================
optimization:
  w_hover: [0.0, 0.25, 0.5, 0.75, 1.0] # Weighting for hover in multi-objective optimization
  # Kappa controls the exploration-exploitation trade-off.
  # Higher kappa = more exploration of uncertain regions.
  kappa: 2.0