# =========================
# PATHS
# =========================
paths:
  # --- Data Directories ---
  data_hover_comsol:   "../Experiment/data/hover/comsol"
  data_hover_raw:   "../Experiment/data/hover/raw"
  data_hover_tare:  "../Experiment/data/hover/tare"
  data_cruise_comsol:   "../Experiment/data/cruise/comsol"
  data_cruise_raw:  "../Experiment/data/cruise/raw"
  data_cruise_tare: "../Experiment/data/cruise/tare"
  data_processed_dir: "../Experiment/data/processed" # Renamed for clarity

  # --- Key File Paths ---
  master_parquet:   "../Experiment/data/processed/master_dataset.parquet"
  doe_csv:          "../Experiment/doe/doe_test_plan_01.csv"

  # --- Output Directories ---
  outputs_models:   "../Experiment/outputs/models"
  outputs_plots:    "../Experiment/outputs/plots"
  outputs_tables:   "../Experiment/outputs/tables"

# =========================
# DATA PROCESSING PARAMETERS
# =========================
hover_process:
  # SNR thresholds for automatic data filtering
  thrust_snr_threshold: 3.0
  torque_snr_threshold: 3.0

cruise_process:
  airspeed_filter_ms: [18.0, 22.0] # Filters data to only include points within this speed range (m/s)
  drag_moment_arm_m: 0.070

# =========================
# FLUIDS
# =========================
fluids:
  rho: 1.204   # kg/m^3 density of air at 20C, 1 atm
  mu:  1.81e-5 # Pa·s dynamic viscosity of air at 20C, 1 atm

# =========================
# GEOMETRY (global constants)
# =========================
geometry:
  r_hub_m:        0.046      # hub radius (m)
  span_blade_m:   0.184      # blade span (m) -> r_tip = r_hub_m + span_blade_m
  n_blades:       2          # number of blades

# =========================
# MODEL FEATURES & BOUNDS
# =========================
geometry_cols: ["AR", "lambda", "aoa_root (deg)", "twist (deg)"]

bounds:
  AR:             [18.75, 31.25] # Aspect Ratio
  lambda:         [0.5, 1.0]   # Taper Ratio
  twist (deg):    [-15, 0] # Twist (tip - root) (degrees)
  op_speed_hover (rpm): [450, 2000]   # Example: Use your actual min/max RPMs
  op_speed_cruise (m/s): [20, 20]    # Example: The range you plan to test in CFD

# =========================
# OPTIMIZATION PARAMETERS
# =========================
optimization:
  w_hover: [0.0, 0.25, 0.5, 0.75, 1.0] # Weighting for hover in multi-objective optimization
  # Set these AoA sweeps to be INSIDE your data range (Hover: 10-20, Cruise: 5-35)
  hover_op_points: [10, 12, 14, 16, 18, 20]  # A good sweep within your hover data
  cruise_op_points: [5, 8, 11, 14, 17, 20]   # Covers the likely area of max L/D